### ISSUE TITLE
Error on Conversion

### ISSUE THREAD

**Issue by madhavsund** [ccoreilly/wav2vec2-service#1]
tried 
python convert_torch_to_onnx.py --model model_path

Error

Traceback (most recent call last):
  File "convert_torch_to_onnx.py", line 1, in <module>
    from onnxruntime.quantization.quantize import quantize
  File "/home/krc/.local/lib/python3.7/site-packages/onnxruntime/quantization/__init__.py", line 1, in <module>
    from .quantize import quantize, quantize_static, quantize_dynamic, quantize_qat
  File "/home/krc/.local/lib/python3.7/site-packages/onnxruntime/quantization/quantize.py", line 7, in <module>
    import onnx
  File "/project/shobana_development/onnx_models/wav2vec2-service-master/onnx.py", line 13, in <module>
    session = rt.InferenceSession(ONNX_PATH, sess_options)
  File "/home/krc/.local/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 335, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/home/krc/.local/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 368, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from wav2vec2.onnx failed:Load model wav2vec2.onnx failed. File doesn't exist

**Comment by ccoreilly** [comment]
The `onnx` package was missing in the `requirements.txt` and the `onnx.py` was being imported. Please pull the latest changes and try again (rerun `pip install -r requirements.txt`)
